targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include: [
            "lib/states/*.dart",
            "lib/states/responses/*.dart"
          ]
      freezed:
        generate_for:
          include: [
            "lib/states/*.dart",
            "lib/states/responses/*.dart"
          ]